spring:
  datasource:
    url: jdbc:mysql://34.64.160.57:3306/test?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: aa88sd
    password: rlatnehd@123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true