name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps :
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
  
      - name: Permission
        run: chmod 744 gradlew
  
      - name: Build
        run: ./gradlew clean build

      - name: Build the Docker image
        run: docker build -t ${{secrets.DOCKER_USERNAME}}/${{secrets.DOCKER_REPOSITORY}} .

      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Docker Push
        run: docker push ${{secrets.DOCKER_USERNAME}}/${{secrets.DOCKER_REPOSITORY}}

      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{secrets.HOST_IP}}
          port: 22
          passphrase: ${{secrets.HOST_PASSPHARSE}}
          username: ${{secrets.HOST_USERNAME}}
          key: ${{secrets.HOST_KEY}}
          script: |
            sudo docker stop ${{secrets.DOCKER_REPOSITORY}}
            sudo docker rm ${{secrets.DOCKER_REPOSITORY}}
            sudo docker pull ${{secrets.DOCKER_USERNAME}}/${{secrets.DOCKER_REPOSITORY}}
            sudo docker run --name ${{secrets.DOCKER_REPOSITORY}} -d -p 8080:8081 ${{secrets.DOCKER_USERNAME}}/${{secrets.DOCKER_REPOSITORY}}
          
